sudo: required
env:
  global:
  matrix:
  - IMAGE=centos:centos6 COMPONENTS=udt,myproxy,ssh
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2cca008ad2c8_key -iv $encrypted_2cca008ad2c8_iv -in magicfile.txt.enc -out magicfile.txt -d
#- sudo apt-get update
#- sleep 5
#- sudo docker pull ${IMAGE}
script:
- echo magic file contents are && cat magicfile.txt
