sudo: required
env:
    matrix:
    - OS_VERSION=6 COMPONENTS=udt,myproxy
    - OS_VERSION=7 COMPONENTS=udt,myproxy
    - OS_VERSION=6 COMPONENTS=gram5
    - OS_VERSION=7 COMPONENTS=gram5

services:
    - docker

before_install:
    - sudo apt-get update
    - sleep 5
    - sudo docker pull centos:centos${OS_VERSION}

script:
- travis-ci/setup_tests.sh ${COMPONENTS}

