language: cpp

git:
    depth: 3

addons:
    apt:
        packages:
        - gcc
        - g++
        - make
        - autoconf
        - automake
        - libtool
        - patch
        - libltdl-dev
        - openssl
        - libssl-dev
        - git
        - liburi-perl

install: true

before_script:
- rm -f prep-gsissh gsi_openssh.gt6.diff
- autoreconf -if
- ./configure --disable-gsi-openssh --disable-gram5

script:
- make -j  &&  make -j check

