sudo: required
secure: "rSWNz6vKHQVnHdwCuUyN2tzv0u8/4nOCYhh1vOtfyRhoJQvvARnkoctydxdJrxkPOflTDJ0bY+0SFiJZC/l5cKcSSZMiyl7Fl/PDEJDKzroam0P5EpL3p+WPqJ8YIgh6o6EJckJya7IisorgkzT4z6czOjFN562AcAd3UrzGm6HdsjnlGd15WCPTEQNJSxT5b5WNAc4OZ7Fu3OVyCY00BjuENecwDPEl9BuqOKhT1VAy0Ah4GVQViCq11pOx1Jzf5sGG9YqSPq1Wi9rm1Br2xYxoFmJaVRokmVlpBuElUicNkUjeL3e9pVD2VDClKWclhAxf0LcJedHdr7H/zj+H7cM83kVgjc5aS/3VcSIY3+yJZZmqysWi/tUwFnK444gsrCH78I7ncb9xVEd+vDL/RLyvb50nyLGWc0XNUW31n1nv3omsidFIPIkiQFQsy1ET6LUJzI4VFsy7brpmJQhO7fgrNF/aHwfJruR5EmqeSWePFCg/b6QyOqHYLefh2MhY1yL/bDkqSATA58lLF2geRA9UilZONxx0ON8IKS3msh9kHyWnKvut4BTJS2x1adV95fr266avoa6CQxkpSaYhZTmSkuzE1vnXEQr5drvVMHR9t1RUl2v+P3w+mrXIbDpjGNOnNTxEWpDS8oSP8LsstHMOQ6RYPDI4mUvAQ9Mk31o="
env:
    matrix:
    - IMAGE=centos:centos6 COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos7 COMPONENTS=udt,myproxy,ssh
#   Fedora builds are implemented but are disabled until we decide we
#   need them; Travis limits our number of concurrent jobs so we don't
#   want more than are necessary.
#    - IMAGE=fedora:25      COMPONENTS=udt,myproxy,ssh
#    - IMAGE=fedora:26      COMPONENTS=udt,myproxy,ssh
#    - IMAGE=fedora:27      COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos6 COMPONENTS=gram5
    - IMAGE=centos:centos7 COMPONENTS=gram5
#   The following gram tests failed for all fedora versions:
#       nonblocking-register-test.pl, register-callback-test.pl, register-test.pl
#    - IMAGE=fedora:25      COMPONENTS=gram5
#    - IMAGE=fedora:26      COMPONENTS=gram5
#    - IMAGE=fedora:27      COMPONENTS=gram5

services:
    - docker

before_install:
    - sudo apt-get update
    - sleep 5
    - sudo docker pull ${IMAGE}

script:
- echo the magic word is \"$MAGICWORD\"
#- travis-ci/setup_tests.sh

