sudo: required
env:
    matrix:
    - IMAGE=centos:centos6 COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos7 COMPONENTS=udt,myproxy,ssh
    - IMAGE=fedora:25      COMPONENTS=udt,myproxy,ssh
    - IMAGE=fedora:26      COMPONENTS=udt,myproxy,ssh
    - IMAGE=fedora:27      COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos6 COMPONENTS=gram5
    - IMAGE=centos:centos7 COMPONENTS=gram5
    - IMAGE=fedora:25      COMPONENTS=gram5
    - IMAGE=fedora:26      COMPONENTS=gram5
    - IMAGE=fedora:27      COMPONENTS=gram5

services:
    - docker

before_install:
    - sudo apt-get update
    - sleep 5
    - sudo docker pull ${IMAGE}

script:
- travis-ci/setup_tests.sh

