sudo: required
env:
    matrix:
    - IMAGE=centos:centos6 TASK=tests COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos7 TASK=tests COMPONENTS=udt,myproxy,ssh
#   Fedora builds are implemented but are disabled until we decide we
#   need them; Travis limits our number of concurrent jobs so we don't
#   want more than are necessary.
#    - IMAGE=fedora:25     TASK=tests COMPONENTS=udt,myproxy,ssh
#    - IMAGE=fedora:26     TASK=tests COMPONENTS=udt,myproxy,ssh
#    - IMAGE=fedora:27     TASK=tests COMPONENTS=udt,myproxy,ssh
    - IMAGE=centos:centos6 TASK=tests COMPONENTS=gram5
    - IMAGE=centos:centos7 TASK=tests COMPONENTS=gram5
#   The following gram tests failed for all fedora versions:
#       nonblocking-register-test.pl, register-callback-test.pl, register-test.pl
#    - IMAGE=fedora:25      TASK=tests COMPONENTS=gram5
#    - IMAGE=fedora:26      TASK=tests COMPONENTS=gram5
#    - IMAGE=fedora:27      TASK=tests COMPONENTS=gram5
    - IMAGE=centos:centos7 TASK=tarballs COMPONENTS=ssh,gram5


services:
    - docker

before_install:
    - sudo apt-get update
    - sleep 5
    - sudo docker pull ${IMAGE}

script:
- travis-ci/setup_tests.sh

